### ISSUE TITLE
notebook

### ISSUE THREAD

**Issue by yangche7** [amckenna41/pySAR#1]
Hi, 
Thanks for creating such nice repo for analysing sequence-function relationship ! 

I am just wondering would you release a notebook that guide the users how to use it to build the model ? 
Thanks a lot !
Bt, Che

**Comment by amckenna41** [comment]
Hi Che,

Thanks for your interest in my repo. I have been meaning to make a step-by-step jupyter notebook on how to use the repo and software as well as creating some documentation. Hoping to release both of these soon.

Thanks!
AJ.

**Comment by yangche7** [comment]
Hi AJ, 
Sounds awesome !
Looking forward to that.
And I therefore close this issue :)
Bt, Che

**Comment by amckenna41** [comment]
Hi @yangche7 , just letting you know that the example notebook discussed above is available here: https://colab.research.google.com/drive/1hxtnf8i4q13fB1_2TpJFimS5qfZi9RAo?usp=sharing . Hopefully it helps with your analysis.
