### ISSUE TITLE
How I get the column name for "descriptors_thermostability.csv"?

### ISSUE THREAD

**Issue by rupeshagarwal** [amckenna41/pySAR#2]
There are a bunch of column names like "A,B.." and so on in the file descriptors_thermostability.csv. How do I know what these columns correspond to?

**Comment by amckenna41** [comment]
Each of the columns in the pre-calculated descriptors csv file represent the individual features for each of the protein descriptors. So for example "A,C,D,E..." are the amino acid composition, "AA,AC,AD..." are the dipeptide composition, "QSO_SW1,QSO_SW2..." are the quasi sequence order descriptors etc. 

I've added a bullet-pointed list of the descriptors and their individual dimensions in the csv file to the /data/README.md file (https://github.com/amckenna41/pySAR/tree/master/data). Hopefully that helps!
